--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    client_id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    monthly_visits integer NOT NULL,
    birth_date timestamp(6) without time zone
);


ALTER TABLE public.client OWNER TO postgres;

--
-- Name: client_client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN client_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kart; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kart (
    kart_id bigint NOT NULL,
    code character varying(255),
    state integer NOT NULL
);


ALTER TABLE public.kart OWNER TO postgres;

--
-- Name: kart_kart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kart ALTER COLUMN kart_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kart_kart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservation (
    reservation_id bigint NOT NULL,
    contact_client character varying(255),
    number_of_people integer NOT NULL,
    reservation_code character varying(255) NOT NULL,
    reservation_date date,
    reservation_end_time time(6) without time zone,
    reservation_start_time time(6) without time zone,
    tariff_id bigint NOT NULL,
    status integer NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public.reservation OWNER TO postgres;

--
-- Name: reservation_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservation_detail (
    reservation_detail_id bigint NOT NULL,
    applied_discount double precision NOT NULL,
    basic_tariff_applied double precision NOT NULL,
    client_name character varying(255),
    final_amount double precision NOT NULL,
    kart_id bigint,
    reservation_id bigint NOT NULL
);


ALTER TABLE public.reservation_detail OWNER TO postgres;

--
-- Name: reservation_detail_reservation_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservation_detail ALTER COLUMN reservation_detail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_detail_reservation_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservation ALTER COLUMN reservation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tariff; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tariff (
    tariff_id bigint NOT NULL,
    base_price double precision NOT NULL,
    booking_type integer NOT NULL,
    reservation_duration integer NOT NULL
);


ALTER TABLE public.tariff OWNER TO postgres;

--
-- Name: tariff_tariff_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tariff ALTER COLUMN tariff_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tariff_tariff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client (client_id, email, name, monthly_visits, birth_date) FROM stdin;
3	sofia@gmail.com	Sofia Belen Gacitua Lopez	0	2002-11-25 00:00:00
4	sofia@gmail.com	Sofia Belen Gacitua	0	2002-11-24 21:00:00
7	sofia@gmail.com	sofita Gacitua	0	2025-03-31 21:00:00
8	josejose@gmail.com	jose	0	2001-10-08 20:00:00
9	francisco@gmail.com	francisco	0	2002-01-31 21:00:00
10	nicolas@gmail.com	Nicolas Garcia	0	2003-03-09 20:00:00
11	Frankkk@gmail.com	Frank	0	2003-01-31 21:00:00
\.


--
-- Data for Name: kart; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kart (kart_id, code, state) FROM stdin;
0	K001	0
1	K002	0
2	K003	0
3	K004	0
4	K005	0
5	K006	0
6	K007	0
7	K008	0
8	K009	0
9	K010	0
10	K011	0
11	K012	0
12	K013	0
13	K014	0
14	K015	0
\.


--
-- Data for Name: reservation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservation (reservation_id, contact_client, number_of_people, reservation_code, reservation_date, reservation_end_time, reservation_start_time, tariff_id, status, client_id) FROM stdin;
1	\N	4	a6541bf5	2025-04-28	01:00:00	14:00:00	1	2	10
2	\N	1	61508bf9	2025-06-12	06:00:00	14:00:00	2	2	8
3	\N	7	d0fe50ec	2026-02-25	17:35:00	17:00:00	1	1	11
4	\N	6	297547e0	2026-05-29	15:30:00	15:00:00	0	1	10
\.


--
-- Data for Name: reservation_detail; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservation_detail (reservation_detail_id, applied_discount, basic_tariff_applied, client_name, final_amount, kart_id, reservation_id) FROM stdin;
\.


--
-- Data for Name: tariff; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tariff (tariff_id, base_price, booking_type, reservation_duration) FROM stdin;
0	15000	0	30
1	20000	1	35
2	25000	2	40
\.


--
-- Name: client_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_client_id_seq', 11, true);


--
-- Name: kart_kart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kart_kart_id_seq', 1, false);


--
-- Name: reservation_detail_reservation_detail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservation_detail_reservation_detail_id_seq', 1, false);


--
-- Name: reservation_reservation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservation_reservation_id_seq', 4, true);


--
-- Name: tariff_tariff_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tariff_tariff_id_seq', 1, false);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (client_id);


--
-- Name: kart kart_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kart
    ADD CONSTRAINT kart_pkey PRIMARY KEY (kart_id);


--
-- Name: reservation_detail reservation_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation_detail
    ADD CONSTRAINT reservation_detail_pkey PRIMARY KEY (reservation_detail_id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (reservation_id);


--
-- Name: tariff tariff_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tariff
    ADD CONSTRAINT tariff_pkey PRIMARY KEY (tariff_id);


--
-- Name: reservation ukb16r178jxqqmyfum9swkjtri9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT ukb16r178jxqqmyfum9swkjtri9 UNIQUE (reservation_code);


--
-- Name: reservation fk3x37weqmcqk89lgiof13e99i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk3x37weqmcqk89lgiof13e99i FOREIGN KEY (tariff_id) REFERENCES public.tariff(tariff_id);


--
-- Name: reservation_detail fk5ktlm47vj7tew1ucmeib7dv7m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation_detail
    ADD CONSTRAINT fk5ktlm47vj7tew1ucmeib7dv7m FOREIGN KEY (kart_id) REFERENCES public.kart(kart_id);


--
-- Name: reservation_detail fk8l2lrhs3c27q2tg7glsv8oouj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation_detail
    ADD CONSTRAINT fk8l2lrhs3c27q2tg7glsv8oouj FOREIGN KEY (reservation_id) REFERENCES public.reservation(reservation_id);


--
-- Name: reservation fkoewar6f18rkn4iptr6da4oysv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkoewar6f18rkn4iptr6da4oysv FOREIGN KEY (client_id) REFERENCES public.client(client_id);


--
-- PostgreSQL database dump complete
--

